import NavBar from "@/app/components/NavBar"

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }
  
  export default function Layout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <div>
          <NavBar />
          {children}
      </div>
    )
  }